[package]
name = "typst_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
color-eyre = "0.6.5"
surveyhero = { path = "../../surveyhero/" }
typst = "0.14.2"
typst-kit = "0.14.2"
time = "0.3.45"
typst-pdf = "0.14.2"
